[workspace]
members = ["kvlr", "kvlr-server", "kvlr-client", "kvlr-derives"]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1
debug-assertions = false
# codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false

